theme: jekyll-theme-minimal
title: oofybruh9's blog
description: blog of the funni
permalink: none
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
paginate: 5
