# 1. Site Settings
title               : 'blog of the funni'
owner               : "oofybruh9"
url                 : "https://oofybruh9.is-a.dev"
baseurl             : ""
permalink           : /:title/
description         : "the funny oofybruh9 blog of sorts"
markdown            : kramdown
statement           : "designed by DeerRIDER, used by oofybruh9, All Rights Reserved"
bgtext              : "01"


# 2. Collections
collections:
  portfolio:
    output          : true
    permalink       : /:collection/:title/
  album:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
  game:
    output          : true
    permalink       : /:collection/:title/
  lore:
    output          : true
    permalink       : /:collection/:title/
  music:
    output          : true
    permalink       : /:collection/:title/
  my_notes:
    output          : true
    permalink       : /:collection/:title/
    # An alias should be given or the UNDERSCORE will appeared 
    alias           : "My Notes"
  posts:
    output          : true

# 4. Default page configuration
defaults:
  -    
    scope:
      path          : ""  # an empty string here means all files in the project
    values:
      layout              : "post"      # which layout to use by default
      publish             : true        # whether to show by default      
      btn_text            : true        # whether show button text by default
      collection_list     : true        # whether show archive button by default
      home_btn            : true        # whether show home by default
      maximize            : true        # whether show maximize button by default
      encrypted_text      : false       # whether use encrytion function by default
      toc                 : true        # whether show table of content by default
      toc_level           : 3           # the toc depth by default
      author              : true        # author name by default
      show_date           : true        # whether show date message by default
      category            : true        # category by default
      post_list           : true        # whether show list of post by default      
      comment             : true
      footer              : true        # whether show footer by default
      highlight           : false

# 5. Social Media Accounts
email               : "oofybruh@gmail.com" 
linkedin            : 
github              : "oofybruh9" 
gitlab              : 
website             : "#"
twitter             : "oofybruh9"
facebook            : 
instagram           : 
youtube             : "oofybruh9"
steam               : "oofybruh9"
weibo               :

# 6. Where things are
source              : .
assets_dir          : assets
destination         : ./_site
collections_dir     : collections
plugins_dir         : src/_plugins  # takes an array of strings and loads plugins in that order
layouts_dir         : src/_layouts
data_dir            : src/_data
includes_dir        : src/_includes
sass:
  sass_dir          : src/_sass

# User defined paths
# When inserting images, could use "{{site.img}}/path/to/image.png" instead
img                : /images      

# 7. Plugins

plugins:
  - jekyll-feed
  - jekyll-sitemap
 # - jekyll-seo-tag
  - jekyll-mermaid

# 8. JS version
# Search Plugins on: https://cdnjs.com/
# This is functioned in ./src/_includes/head.html
mathjax_version     : "3.2.2"
mermaid_version     : "11.3.0"
fontawesome_version : "4.6.0"

# 9. kramdown settings
kramdown:
#  parse_block_html: true

# 10. Others
# Cross-Origin Resource Sharing header
webrick:
  headers:
   Access-Control-Allow-Origin: "*"


